fail_fast: true
repos:
- repo: local
  hooks:

  - id: isort
    name: isort
    entry: pipenv run isort
    language: python
    types: [python]
    exclude: ai_service_protos/
    args: [-m 3, -tc]

  - id: format
    name: format
    entry: pipenv run format
    language: system
    exclude: ai_service_protos/
    types: [python]
    args: [--in-place]

