fail_fast: true
repos:
- repo: local
  hooks:

  - id: format
    name: format
    entry: pipenv run format
    language: system
    exclude: (?x)^(
        docs/.+ |
        ai_service_protos/
        )$
    types: [python]

